---
- name: Create disable-transparent-huge-pages.service file
  copy:
    src: disable-transparent-huge-pages.service
    dest: /etc/systemd/system/
    owner: root
    group: root
  become: true

- name: Start disable-transparent-huge-pages service
  systemd:
    state: started
    name: disable-transparent-huge-pages.service
    enabled: true
    daemon_reload: true
  become: true
...